// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVg5LMlQShrQR-hyHEfYgSqta0laQOt9Q',
    appId: '1:499440037778:web:d061251390ae9cb22e9b4b',
    messagingSenderId: '499440037778',
    projectId: 'dome-965fa',
    authDomain: 'dome-965fa.firebaseapp.com',
    storageBucket: 'dome-965fa.firebasestorage.app',
    measurementId: 'G-CNWJRB44PJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyngs9P4FZusa4yVo1enSNtdSlJDamcm4',
    appId: '1:499440037778:android:6c08d79f1d74ff8a2e9b4b',
    messagingSenderId: '499440037778',
    projectId: 'dome-965fa',
    storageBucket: 'dome-965fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4S-1dt5wvdnJ1U0YuZ_3yUL2u15zzwxU',
    appId: '1:499440037778:ios:384a5bb5fede59a22e9b4b',
    messagingSenderId: '499440037778',
    projectId: 'dome-965fa',
    storageBucket: 'dome-965fa.firebasestorage.app',
    iosBundleId: 'com.example.sabak21FirebaseAdd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4S-1dt5wvdnJ1U0YuZ_3yUL2u15zzwxU',
    appId: '1:499440037778:ios:384a5bb5fede59a22e9b4b',
    messagingSenderId: '499440037778',
    projectId: 'dome-965fa',
    storageBucket: 'dome-965fa.firebasestorage.app',
    iosBundleId: 'com.example.sabak21FirebaseAdd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVg5LMlQShrQR-hyHEfYgSqta0laQOt9Q',
    appId: '1:499440037778:web:c775598dc1a5e83a2e9b4b',
    messagingSenderId: '499440037778',
    projectId: 'dome-965fa',
    authDomain: 'dome-965fa.firebaseapp.com',
    storageBucket: 'dome-965fa.firebasestorage.app',
    measurementId: 'G-8H521S1RHZ',
  );
}
